BROKER_ADRESS = "test.mosquitto.org"
PORT = 1883 
TOPIC_LED = "mindset/led"
TOPIC_BUZZER = "mindset/buzzer"
TOPIC_LIST = ["mindset/led", "mindset/buzzer", "mindset/relay"]
DISPLAY_TOPIC = "mindset/display"
POWER_THRESHOLD = 0.7
TOPIC_IDX = 0
TOPIC_TOGGLE = False